name: Deploy Lovable via FTP na Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      # Configura o Bun para instalar dependências e fazer o build
      - name: Configurar o Bun
        uses: oven-sh/setup-bun@v1

      - name: Instalar dependências com Bun
        run: bun install

      - name: Build do projeto com Bun
        run: bun run build

      - name: Mostrar arquivos gerados
        run: ls -al dist/

      # Envia os arquivos para o diretório correto na Hostinger
      - name: Deploy FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: dist/
          server-dir: public_html/ # <-- VERIFIQUE ESTE DIRETÓRIO!
          dangerous-clean-slate: true
          dry-run: false
          log-level: verbose
